{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "031654be",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Тесты для исключительных случаев\"\"\"\n",
    "# Чтобы протестировать функции - надо создать файлы в директории программы, названия которых приведены ниже\n",
    " \n",
    "# Тестирование исключения FileNotFoundError для функции load_table_csv\n",
    "try:\n",
    "    table = load_table_csv(\"nonexistent_file.csv\")\n",
    "except FileNotFoundError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения ValueError для функции load_table_csv\n",
    "try:\n",
    "    table = load_table_csv(\"invalid_format.csv\")\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения ValueError для функции save_table_csv\n",
    "try:\n",
    "    table = {\"Name\": [\"Sasha\", \"Kate\"], \"Age\": [18, 19, 35]}\n",
    "    save_table_csv(table, \"invalid_table.csv\")\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения FileNotFoundError для функции load_table_pickle\n",
    "try:\n",
    "    table = load_table_pickle(\"nonexistent_file.pickle\")\n",
    "except FileNotFoundError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения ValueError для функции load_table_pickle\n",
    "try:\n",
    "    table = load_table_pickle(\"invalid_format.pickle\")\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения ValueError для функции save_table_pickle\n",
    "try:\n",
    "    table = {\"Name\": [\"Sasha\", \"Kate\"], \"Age\": [18, 19, 35]}\n",
    "    save_table_pickle(table, \"invalid_table.pickle\")\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тестирование исключения ValueError для функции save_table_text\n",
    "try:\n",
    "    table = {\"Name\": [\"Sasha\", \"Kate\"], \"Age\": [18, 19, 35]}\n",
    "    save_table_text(table, \"invalid_table.txt\")\n",
    "except ValueError as e:\n",
    "    print(e)\n",
    " \n",
    "# Тесты для функции get_rows_by_number\n",
    "# 1. Попытка получить строки с некорректными номерами\n",
    "get_rows_by_number(-1)  # Ожидаемое исключение: ValueError\n",
    "get_rows_by_number(10, 5)  # Ожидаемое исключение: ValueError\n",
    " \n",
    "# Тесты для функции get_rows_by_index\n",
    "# 2. Попытка получить строки с некорректными значениями\n",
    "get_rows_by_index('abc', 'def')  # Ожидаемое исключение: TypeError\n",
    "get_rows_by_index()  # Ожидаемое исключение: TypeError\n",
    " \n",
    "# Тесты для функции get_column_types\n",
    "# 3. Попытка получить типы столбцов при некорректном аргументе\n",
    "get_column_types('abc')  # Ожидаемое исключение: TypeError\n",
    " \n",
    "# Тесты для функции set_column_types\n",
    "# 4. Попытка задать типы столбцов с некорректным аргументом\n",
    "set_column_types('abc')  # Ожидаемое исключение: TypeError\n",
    " \n",
    "# Тесты для функции get_values\n",
    "# 5. Попытка получить значения из несуществующего столбца\n",
    "get_values(10)  # Ожидаемое исключение: IndexError\n",
    "get_values('column')  # Ожидаемое исключение: KeyError\n",
    " \n",
    "# Тесты для функции get_value\n",
    "# 6. Попытка получить значение из несуществующего столбца\n",
    "get_value(10)  # Ожидаемое исключение: IndexError\n",
    "get_value('column')  # Ожидаемое исключение: KeyError"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
